pollme/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),
    path('polls/', include('polls.urls', namespace='polls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name='polls'

urlpatterns = [

    path('list/', views.polls_list, name='list'),
    #poll/details/1
    path('details/int:<poll_id>/', views.poll_detail, name='detail'),

]

polls/models.py
from django.db import models


class Poll(models.Model):
	
	text = models.CharField(max_length=255)
	pub_date = models.DateField()

	def __str__(self):
		return f'{self.text}'

class Choice(models.Model):
	question = models.ForeignKey(Poll, on_delete = models.CASCADE)
	choice_text = models.CharField(max_length=255)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return f'{self.choice_text}'

pollme/views.py
from django.shortcuts import render


def home(request):
	
	context = {
	
	}
	return render(request, 'home.html', context)

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Poll 

def polls_list(request):
	'''
	Renders the polls list template, which lists all the currently availble polls
	'''
	
	polls = Poll.objects.all()

	context = {
	'polls': polls
	}
	
	return render(request, 'polls/polls_list.html', context)


def poll_detail(request, poll_id):
    """
    Render the poll_detail.html template which allows a user to vote
    on the choices of a poll
    """
    poll = Poll.objects.get(id=poll_id)
    

    context = {'poll': poll}
    return render(request, 'polls/poll_detail.html', context)


# Create your views here.

polls/templates/polls/poll_detail.html
<h1> HELLLLOOOOOOOOO POLL DETAIL </h1>

polls/templates/polls/polls_list.html
{% extends 'base.html' %}

{% block title %}
<title> Welcome to Polls List </title>
{% endblock %}


{% block content %}
<div class="container">
	<h1>
		Welcome to Polls List!
	</h1>

{% for x in polls %}
 <ul>
 	<li> 
 	{{ x }} 
 	</li>
 	
 	<ul>
 	
 	{% for choice in x.choice_set.all %}
 	
 	<li>
 	{{ choice }}
 	</li>
 	
 	{% endfor %}	
 	</ul>
 </ul>
{% endfor %}


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  {% block title %}
    
	{% endblock %}
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  	{% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
<title> Welcome to Home </title>
{% endblock %}


{% block content %}
<h1>
  Hello World
</h1>
<h2>
	Hello World
</h2>
<h3>
	Hello World

</h3>
<h4>
	Hello World
</h4>
<h5>
	Hello World
</h5>
<h6>
	Hello World
</h6>
{% endblock %}

templates/navbar.html
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Robert Neuzil</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'polls:list'  %}">Polls List</a></li>
            
           
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>